### ISSUE TITLE
Sample size in p2cor

### ISSUE THREAD

**Issue by ghost** [privefl/simus-PRS#2]
Hi Florian,
I was wondering if you could let me know what exactly is the argument `n` in `p2cor()`.
For example, in `paper3-SCT/code_real/07-mult-small-CAD.R`, how does `Nss` equal `60801 + 123504`?
What does this "sample size" refer to?

**Comment by privefl** [comment]
This is `Ncase + Ncontrol`.
It may be better to use `4 / (1 / Ncase + 1 / Ncontrol))`, the effective sample size.

**Comment by ghost** [comment]
So is it the same as `nrow(obj.bigSNP$fam)` ? Assuming disease status is stored in fam (and no missing values).

And it just counts `Ncase + Ncontrol` in the training set?

**Comment by privefl** [comment]
It is the sample size of external GWAS summary statistics, not the data you have.

**Comment by ghost** [comment]
Thanks so much Florian! Got it now.
